import '@/styles/global.css'
import '@/styles/fonts.css'
import type { Metadata } from 'next'
import Navbar from '@/components/layout/navbar'
import Sidebar from '@/components/layout/sidebar'
import ThemeProvider from './providers/themeProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <div className="h-screen w-full overflow-hidden">
                    <Navbar />
                    <div className="flex h-full w-full overflow-hidden">
                        <ThemeProvider>
                            <Sidebar isOpen />
                        </ThemeProvider>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
